name: Bump components.yaml on main branch

on:  # yamllint disable-line rule:truthy
  workflow_dispatch: {}
  schedule:
  # Run this every week day at 1AM
  - cron: '0 1 * * 1-5'

jobs:
  bump-payloads:
    name: "Bump payloads"
    runs-on: ubuntu-latest
    if: github.repository_owner == 'tektoncd'  # do not run this elsewhere
    steps:
    - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3  # v6.0.0
    - uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c  # v6.1.0
      with:
        go-version-file: "go.mod"
    - name: run operator-tool bump
      run: |
        export GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
        make components/bump
    - name: create pull request
      uses: peter-evans/create-pull-request@22a9089034f40e5a961c8808d113e2c98fb63676  # v7.0.11
      with:
        token: ${{ secrets.CHATOPS_TOKEN }}
        commit-message: Bump payloads versions
        committer: tekton-bot <tekton-bot@users.noreply.github.com>
        author: Vincent Demeester <vdemeest@redhat.com>
        signoff: true
        # author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        branch: bot-bump-payload
        delete-branch: true
        title: "[bot] bump payload versions"
        labels: |
          release-note-none
